# Generated by Django 3.2.5 on 2023-01-26 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_review_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
